all: 
	jupyter nbconvert --to slides --post serve --SlidesExporter.reveal_theme=sky --SlidesExporter.reveal_scroll=True --SlidesExporter.reveal_transition=cube algebra.ipynb

dev:
	jupyter notebook

publish:
	mv algebra.slides.html index.html
