slide: 
	jupyter nbconvert --to slides --post serve --SlidesExporter.reveal_theme=sky --SlidesExporter.reveal_scroll=True --SlidesExporter.reveal_transition=cube calculus.ipynb

dev:
	jupyter notebook

publish:
	mv calculus.slides.html index.html
