slide: 
	jupyter nbconvert --to slides --SlidesExporter.reveal_theme=sky --SlidesExporter.reveal_scroll=True --SlidesExporter.reveal_transition=cube calculus.ipynb

dev:
	jupyter notebook

publish: slide
	mv calculus.slides.html index.html
