slide: 
	jupyter nbconvert --to slides --SlidesExporter.reveal_theme=league --SlidesExporter.reveal_scroll=True --SlidesExporter.reveal_transition=cube --reveal-prefix https://cdn.jsdelivr.net/npm/reveal.js@3.6.0  calculus.ipynb

dev:
	jupyter notebook

publish:
	mv calculus.slides.html index.html
